name: untitled2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  badges: ^2.0.2
  build_runner: ^2.1.7
  cached_network_image: ^3.2.0
  carousel_slider: ^5.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^1.0.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  shimmer: ^2.0.0
  http: ^0.13.4
  internet_connection_checker: ^1.0.0+1
  provider: ^6.1.2
  shared_preferences: ^2.0.13




dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family: CategoryIcons
      fonts:
        - asset: fonts/CategoryIcons.ttf
    - family: MarkPronormal400
      fonts:
        - asset: fonts/MARKPRO.OTF
          weight: 400
    - family: MarkPronormal500
      fonts:
        - asset: fonts/MARKPRO.OTF
          weight: 500
    - family: MarkPronormal700
      fonts:
        - asset: fonts/MARKPRO.OTF
          weight: 700
    - family: MarkPronormal800
      fonts:
        - asset: fonts/MARKPRO.OTF
          weight: 800
    - family: MarkProbold
      fonts:
        - asset: fonts/MARKPRO-BOLD.OTF

    - family: SFPro
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400

  assets:
    - assets/
    - assets/icons_png/
    - assets/icons_png/phones.png
  uses-material-design: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages